addons:
  sonarcloud:
    organization: "marianemt"
    token: "2230829e8a1fb83a0e6d1c3acbb9211e3459dfcc" #  your security token created in sonarcloud

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar sonar:sonar 